[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java $JAVA_OPTS -jar target/cartas-estudio-0.0.1-SNAPSHOT.jar --spring.profiles.active=railway"
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
protocol = "tcp"
internal_port = 8080

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Dserver.port=$PORT"