[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests && cp target/cartas-estudio.jar app.jar"

[deploy]
startCommand = "java $JAVA_OPTS -jar app.jar --spring.profiles.active=railway --server.port=$PORT"
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
protocol = "tcp"
internal_port = 8080
healthcheck = {path = "/actuator/health", interval = "15s", timeout = "5s"}

[env]
JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Xmx512m"